substitutions:
  mft_name: tuya
  base_name: temphumid
  device_name: "${mft_name}-${base_name}"

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  on_boot:
    priority: -100
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
      - wait_until:
          condition:
            mqtt.connected:
          timeout: 60s
      - component.update: bat_volts
      - component.update: cht_sensor

external_components:
  # use rtttl and dfplayer from ESPHome's dev branch in GitHub
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: i2c_soft
    components: [ i2c ]
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: cht8310
    components: [ cht8310 ]
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: add_deepsleep_bk7231n
    components: [ deep_sleep ]

bk72xx:
  board: cbu
    
logger:
  baud_rate: 115200
  level: INFO
  hardware_uart: UART1

globals:
  - id: ota_mode
    type: bool
    initial_value: 'false'

mqtt:
  broker: !secret mqtt_ipaddr
  username: !secret mqtt_user
  password: !secret mqtt_pwd
  birth_message:
  will_message:
  on_message:
    - topic: ${device_name}/ota_mode
      payload: 'ON'
      then:
        - globals.set:
            id: ota_mode
            value: 'true'
    - topic: ${device_name}/ota_mode
      payload: 'OFF'
      then:
        - globals.set:
            id: ota_mode
            value: 'false'
    - topic: ${device_name}/sensor/Temperature/state
      then:
        - if:
            condition:
              lambda: 'return !id(ota_mode);'
            then:
              - light.turn_on: wifi_status
              - deep_sleep.enter: deep_sleep_1
binary_sensor:
  - platform: gpio
    pin: 
      number: P14
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Button"
    publish_initial_state: true
  - platform: gpio
    id: alert
    pin: 
      number: P7
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Alert"
    publish_initial_state: true
    
output:
  - platform: gpio
    pin: 16
    id: status_led

light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

switch:
  - platform: gpio
    pin: 8
    name: "Power"
    restore_mode: ALWAYS_ON 
  
i2c:
  sda: P22
  scl: P20
  scan: true
  id: bus_a
  softwire: true
  
sensor:
  - platform: cht8310
    temperature:
      name: "Temperature"
      min_temp: 20.0
      max_temp: 30.0
    humidity:
      name: "Humidity"
      min_humid: 10.0
      max_humid: 95.0
    update_interval: never
    sd_mode: false
    conv_time: 4
    address: 0x40
    id: cht_sensor
  - platform: adc
    pin: P23
    name: "Battery Level"
    update_interval: never
    id: bat_volts
    filters:
    - multiply: 2.3

deep_sleep:
  sleep_duration: 
    hours: 1
  run_duration: 
    default: 
      seconds: 10
  bk71xx_gpio_wakeup:
    - number: 14
      pin_mode: low_keep_awake
  id: deep_sleep_1
