#Tuya PIR and Alarm 812WT
substitutions:
  mft_name: tuya
  base_name: pirbattery
  name: "${mft_name}-${base_name}"
  ota: "input_boolean.${mft_name}_${base_name}_ota"

esphome:
  name: ${name}
  friendly_name: ${name}
  name_add_mac_suffix: true
  project: 
    name: cap9qd.tuya-pirbattery
    version: "1.0"
  on_boot:
    priority: -100
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
      - logger.log: "Waiting for the API to connect..."
      - wait_until:
          condition:
            api.connected:
      - if:
          condition:
            api.connected:
          then:
            - logger.log: "API Connected"
          else:
            - logger.log: "API NOT Connected"  
      - delay: 2s
      - if:
          condition:
            binary_sensor.is_on: prevent_deep_sleep
          then:
            - deep_sleep.prevent: deep_sleep_1
            - logger.log: "Waiting for OTA Update..."
            - repeat:
                count: 150
                then:
                  - delay: 2s
            - script.execute: turnoff_ha_ota
            - logger.log: "Give up waiting on OTA..."
            - deep_sleep.allow: deep_sleep_1
          else:
            - component.update: bat_volts
            - logger.log: 'Entering Deep Sleep'
      - light.turn_off: wifi_status
      - deep_sleep.enter: deep_sleep_1

external_components:
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: bk7231x_Deep_Sleep
      #ref: add_deepsleep_bk7231n
    refresh: 30s
    components: [ deep_sleep ]

dashboard_import:
  package_import_url: github://cap9qd/esphome_yaml/tuya-pirbattery.yml
  
bk72xx:
  board: cbu
  
logger:
  baud_rate: 115200
  level: DEBUG
  hardware_uart: UART1

web_server:
  port: 80

captive_portal:

api:

ota:

mdns:

wifi:
  ap:
    ssid: ${name} AP
    
button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason

binary_sensor:
  - platform: gpio
    id: button_input
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
      allow_other_uses: true
    name: Button
    publish_initial_state: true     # This is important!
  - platform: gpio
    id: pir_input
    name: PIR Input
    pin: 
      number: P22
      mode: INPUT
      allow_other_uses: true
    publish_initial_state: true     # This is important!
  - platform: homeassistant
    id: prevent_deep_sleep
    entity_id: ${ota}
    publish_initial_state: true     # This is important!
 
switch:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

output:
  - platform: gpio
    pin: P20
    id: status_led
    inverted: true

light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

sensor:
  - platform: adc
    pin: P23
    name: "Battery Voltage"
    id: bat_volts
    update_interval: never
    filters:
      - multiply: 2.3

deep_sleep:
  sleep_duration: 
    hours: 1
  run_duration: 
    default: 
      seconds: 10
#  bk71xx_gpio_wakeup:
#    - pin: 
#        number: 14
#        allow_other_uses: true
#      pin_mode: low_keep_awake
#    - pin: 
#        number: 22
#        allow_other_uses: true
#      pin_mode: high_keep_awake
  id: deep_sleep_1
  

script: 
  - id: turnoff_ha_ota
    then:
      - homeassistant.service:
          service: input_boolean.turn_off
          data:
            entity_id: ${ota}
