#Tuya PIR and Alarm 812WT
substitutions:
  mft_name: tuya
  base_name: pirbattery
  device_name: "${mft_name}-${base_name}"
  ota: "input_boolean.${mft_name}_${base_name}_ota"

esphome:
  name: ${device_name}
  friendly_name: ${device_name}
  name_add_mac_suffix: true
  project: 
    name: cap9qd.tuya-pirbattery-mqtt
    version: "1.0"
  on_boot:
    priority: -100
    then:
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 100ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
      
external_components:
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: bk7231x_Deep_Sleep
    refresh: 10s
    components: [ deep_sleep ]

bk72xx:
  board: cbu
  
logger:
  baud_rate: 115200
  level: VERY_VERBOSE
  hardware_uart: UART1

web_server:
  port: 80

captive_portal:

globals:
  - id: ota_mode
    type: bool
    initial_value: 'true' #Default to true; retain topic will overwrite once MQTT connects.

mqtt:
  broker: 'homeassistant.local'
  port: 1883
  
  will_message: 
    topic: ${device_name}/status
    payload: "online"
    
  on_message:
    - topic: ${device_name}/ota_mode
      payload: 'ON'
      then:
        - globals.set:
            id: ota_mode
            value: 'true'
        - logger.log: "OTA_MODE 'ON'"
    - topic: ${device_name}/ota_mode
      payload: 'OFF'
      then:
        - globals.set:
            id: ota_mode
            value: 'false'
        - logger.log: "OTA_MODE 'OFF'"
  on_connect: 
    then:
      - wait_until:
          condition:
            lambda: 'return !id(ota_mode);'
          timeout: 60s
      - component.update: bat_volts
      #- component.update: button_input
      #- component.update: pir_input
      - logger.log: 'Entering Deep Sleep'
      - deep_sleep.enter: deep_sleep_1

ota:
  - platform: esphome
  
mdns:

wifi:
  ap:
    ssid: ${device_name} AP
    
button:
  - platform: restart
    name: Restart

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason

binary_sensor:
  - platform: gpio
    id: button_input
    pin:
      number: P14
      inverted: true
      mode: INPUT_PULLUP
      allow_other_uses: true
    name: Button
    trigger_on_initial_state: true     # This is important!
  - platform: gpio
    id: pir_input
    name: PIR Input
    pin: 
      number: P22
      mode: INPUT
      allow_other_uses: true
    trigger_on_initial_state: true     # This is important!
 
switch:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"

output:
  - platform: gpio
    pin: P20
    id: status_led
    inverted: true

light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

sensor:
  - platform: adc
    pin: P23
    name: "Battery Voltage"
    id: bat_volts
    update_interval: never
    filters:
      - multiply: 2.3

deep_sleep:
  sleep_duration: 60min
#  run_duration: 10sec
  bk71xx_gpio_wakeup:
    - pin: 
        number: 14
        allow_other_uses: true
      pin_mode: low_keep_awake
    - pin: 
        number: 22
        allow_other_uses: true
      pin_mode: SWAP_LEVEL #high_keep_awake
  id: deep_sleep_1
