substitutions:
  mft_name: tuya
  base_name: temphumid
  device_name: "${mft_name}-${base_name}"
  
esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  project:
    name: cap9qd.tuya-temphumid-mqtt
    version: "0.3"
  on_boot:
    priority: -100
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - logger.log: "WiFi Connected!"
      - light.turn_on: wifi_status
mdns:
external_components:
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: i2c_soft
    components: [ i2c ]
    refresh: 10s
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: cht8310
    components: [ cht8310 ]
    refresh: 10s
  - source:
      type: git
      url: https://github.com/cap9qd/esphome
      ref: bk7231x_Deep_Sleep
    components: [ deep_sleep ]
    refresh: 10s

bk72xx:
  board: cbu

ota:
  - platform: esphome
    on_end:
      - mqtt.publish:
          topic: '${device_name}/ota_mode'
          payload: 'OFF'
          retain: true

logger:
  baud_rate: 0
  level: INFO
  hardware_uart: UART1

globals:
  - id: ota_mode
    type: bool
    initial_value: 'true' #Default to true; retain topic will overwrite once MQTT connects.
  - id: updates
    type: int
    restore_value: no
    initial_value: '0'

mqtt:
  broker: 'homeassistant.local'
  port: 1883
  
  will_message: 
    topic: ${device_name}/status
    payload: "online"
    
  on_message:
    - topic: ${device_name}/ota_mode
      payload: 'ON'
      then:
        - globals.set:
            id: ota_mode
            value: 'true'
        - logger.log: "OTA_MODE 'ON'"
    - topic: ${device_name}/ota_mode
      payload: 'OFF'
      then:
        - globals.set:
            id: ota_mode
            value: 'false'
        - logger.log: "OTA_MODE 'OFF'"
  on_connect: 
    then:
      - wait_until:
          condition:
            lambda: 'return !id(ota_mode);'
          timeout: 60s
      # This serves two purposes: 1- Turn off OTA mode on timeout and 2- Generate ota_mode topic on first install/execute
      - mqtt.publish:
          topic: ${device_name}/ota_mode
          payload: 'OFF'
          retain: True
      - component.update: bat_volts
      - component.update: cht_sensor
      - wait_until:
          condition:
            lambda: |-
              return (id(updates) >= 3);
          timeout: 60s
      - deep_sleep.enter: deep_sleep_1

binary_sensor:
  - platform: gpio
    pin: 
      number: P14
      inverted: true
      mode:
        input: true
        pullup: true
      allow_other_uses: true
    name: "Button"
    publish_initial_state: true
  - platform: gpio
    id: alert
    pin: 
      number: P7
      inverted: true
      mode:
        input: true
        pullup: true
      allow_other_uses: true
    name: "Alert"
    publish_initial_state: true
    
output:
  - platform: gpio
    pin: 16
    id: status_led

light:
  - platform: binary
    id: wifi_status
    output: status_led
    restore_mode: ALWAYS_ON

switch:
  - platform: gpio
    pin: 8
    name: "Power"
    restore_mode: ALWAYS_ON 
  
i2c:
  sda: P22
  scl: P20
  scan: false
  id: bus_a
  #softwire: true
  
sensor:
  - platform: cht8310
    temperature:
      name: "Temperature"
      min_temp: 20.0
      max_temp: 30.0
      on_value: 
        lambda: |-
          id(updates)++;
    humidity:
      name: "Humidity"
      min_humid: 10.0
      max_humid: 95.0
      on_value: 
        lambda: |-
          id(updates)++;
    update_interval: never
    sd_mode: false
    conv_time: 4
    address: 0x40
    id: cht_sensor
  - platform: adc
    pin: P23
    name: "Battery Level"
    update_interval: never
    id: bat_volts
    filters:
    - multiply: 2.3
    on_value: 
      lambda: |-
        id(updates)++;

deep_sleep:
  sleep_duration: 
    hours: 1
  bk71xx_gpio_wakeup:
    - pin
        number: 14
        allow_other_uses: true
      pin_mode: low_keep_awake
    - pin: 
        number: 7
        allow_other_uses: true
      pin_mode: low_keep_awake
  id: deep_sleep_1
